# Generated by Django 3.0 on 2022-04-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
